import type { DeepMerge } from '../utils/types/deep-merge'
import type { DeepRequired } from '../utils/types/deep-required'
import type { LiteralUnion } from '../utils/types/literal-union'

import type { FieldElement } from './fields'
import type { RegisterOptions } from './register'
import type { ValidateResult } from './validation'

/**
 * A record of field names mapped to their errors.
 */
export type InternalFieldErrors = Partial<Record<string, FieldError>>

/**
 * An error generated by a field during validation.
 */
export type FieldError = {
  /**
   * The field element that the error is attached to.
   */
  ref?: FieldElement

  /**
   * If accummulating multiple errors, this is a record of errors mapped to their messages (or true if no message).
   */
  types?: MultipleFieldErrors

  /**
   * The parsed message from the validation rule.
   */
  message?: string
} & (
  | {
      /**
       * Errors of field arrays will be grouped under the `root` property.
       */
      root: FieldError
    }
  | {
      /**
       * All other errors will have a `type` property indicating what kind of error occurred.
       */
      type: LiteralUnion<keyof RegisterOptions, string>
    }
)

/**
 * Options when manually setting an error.
 */
export type ErrorOption = {
  /**
   * The error message.
   */
  message?: string

  /**
   * The error type.
   */
  type?: LiteralUnion<keyof RegisterOptions, string>

  /**
   * A record of errors mapped to their messages.
   */
  types?: MultipleFieldErrors
}

/**
 * Idk.
 */
export type MultipleFieldErrors = {
  [K in keyof RegisterOptions]?: ValidateResult
} & Record<string, ValidateResult>

/**
 * Idk.
 */
export type FieldErrors<T = Record<string, any>> = Partial<FieldErrorsImpl<DeepRequired<T>>> & {
  root?: Record<string, GlobalError> & GlobalError
}

/**
 * Idk.
 */
export type FieldErrorsImpl<T = Record<string, any>> = {
  [K in keyof T]?: K extends 'root' | `root.${string}`
    ? GlobalError
    : T[K] extends object
    ? DeepMerge<FieldError, FieldErrorsImpl<T[K]>>
    : FieldError
}

/**
 * Idk.
 */
export type GlobalError = {
  /**
   * Idk.
   */
  type?: string | number

  /**
   * Idk.
   */
  message?: string
}
